project:
  type: book
  output-dir: docs

book:
  title: "Github tutorial"
  author: "Sarah Endicott"
  date: "2023-06-02"
  chapters:
    - index.qmd
    - setup.qmd
    - git-basics.qmd
    - git-intermediate.qmd
    - misc.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

